# Generated by Django 5.0.6 on 2024-06-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('calificacion_media', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio_servicio', models.IntegerField()),
                ('precio_suscripcion', models.IntegerField()),
                ('calificacion_media', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Despachador',
            fields=[
                ('telefono', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('calificacion_media', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('disponibilidad', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.TextField()),
                ('tamaño', models.CharField(max_length=200)),
                ('personas_porcion', models.CharField(max_length=200)),
                ('precio_plato', models.CharField(max_length=200)),
                ('t_preparacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('vigente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DespachadorDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.delivery')),
                ('despachador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.despachador')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=200)),
                ('hora', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField()),
                ('tiempo', models.CharField(max_length=200)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.delivery')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion_cliente', models.FloatField()),
                ('evaluacion_despacho', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plato')),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurant'),
        ),
        migrations.CreateModel(
            name='ServicioDespachoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despachador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.despachador')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioDespachoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurant')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='DespachadorDetalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despachador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.despachador')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurant')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='DespachadorDeliveryPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurant')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.delivery')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurant')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=200)),
                ('prox_pago', models.CharField(max_length=200)),
                ('ciclo', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.delivery')),
            ],
        ),
        migrations.AddConstraint(
            model_name='suscriptor',
            constraint=models.UniqueConstraint(fields=('cliente', 'delivery'), name='unique_cliente_delivery'),
        ),
    ]
